### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [edson-junior/rock-paper-scissors#9]
Hi, How are you?
Im a graphic designer that like to help projects in opensource for free, so if you like I can contribute with graphic designs,, I can make you a logotype for this project if you want, I like very much your project!
So if you need some design just say it.

Greetings!
Nuno Jesus

**Comment by edson-junior** [comment]
That'd be really cool @nunojesus

**Comment by nunojesus** [comment]
Hello @edson-junior, how are you?
Here is my design for your project, see if you like one of this logos, if you want some color in special just say it that I will make the changes.

Greetings!
Nuno Jesus

![rock papper scissors](https://user-images.githubusercontent.com/34600369/41479965-c24defea-70c4-11e8-987b-704e62afd6e3.png)

**Comment by nunojesus** [comment]
My favorite is the last one :)

**Comment by edson-junior** [comment]
Last one is just perfect. Just send over the image and I'll include it in the readme 😃

**Comment by nunojesus** [comment]
Im happy that you like it, I will send you the png logo files and svg too, do you want more type of files like EPS and PDF?

Greetings!

**Comment by edson-junior** [comment]
I think it's just perfect the way it is. Thank you for your contribution! 😄

**Comment by nunojesus** [comment]
It looks good the logo is one of my favorite logos that I ever made.

If you have other projects like this Im here to help.

greetings!

Nuno Jesus

**Comment by edson-junior** [comment]
Good to know @nunojesus ! I added an acknowledgement note about the logo on the [readme](https://github.com/edson-junior/rock-paper-scissors/blob/master/README.md).
